---
- name: Windows Validation
  hosts: all
  gather_facts: no

  tasks:

    - name: WinRM Validation
      ansible.windows.win_ping:

    - name: Check Windows Update Service
      ansible.windows.win_service:
        name: wuauserv
      register: service_status

    - name: Show service state
      debug:
        var: service_status.state
